sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_d1115d765b55_key -iv $encrypted_d1115d765b55_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a uber.axiom@gmail.com
- sfdx force:org:display -u uber.axiom@gmail.com
- sfdx force:source:push -u uber.axiom@gmail.com
- sfdx force:apex:test:run -u uber.axiom@gmail.com --wait 10
- sfdx force:org:delete -u uber.axiom@gmail.com -p
